# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', markdownx.models.MarkdownxField()),
                ('foto', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
